### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by tiger-regit** [gookit/validate#1]
- If FromRequest func is called, the request body is nil.

- Instance Validation struct every time?
```go
type p struct  {
    Name string "validate:required"
}
type p2 struct  {
    Name2 string "validate:required"
}
p1 := p{Name: "name1"}
p2 := p{Name2: "name2"}
validate.Struct(p1)
validate.Struct(p2)
```
validate.Struct every time return new Validation.
Can instance once Validation?

**Comment by inhere** [comment]
> If FromRequest func is called, the request body is nil. 

? Is there any problem?

> Instance Validation struct every time?

Yes. Because the data to be verified is different every time.

😄 

If you have good ideas and suggestions can be put forward, or sent directly PR

**Comment by tiger-regit** [comment]
All right. I see. thank you
