### ISSUE TITLE
Full Url incorrect

### ISSUE THREAD

**Issue by jdunneirl** [gookit/validate#100]
fullUrl/isFullURL	Check value is full URL string(must start with http,https).

Fails to validate any url with a -

```
https://www.google.com/testme --- works
https://www.google.com/test-me. --fails
```

**Comment by jney** [comment]
@inhere shouldn't full url validation rely on `url.ParseRequestURI` instead on a regex?
The issue is that it will change the current behavior. I think [this](https://github.com/gookit/validate/blob/63696b332109b52a7f50b1503be8977dad2ebfa4/validators_test.go#L484-L485) won't pass anymore

**Comment by inhere** [comment]
update the regex for check url with `-` `_` on 1.3.0
