### ISSUE TITLE
Custom tag implementation 

### ISSUE THREAD

**Issue by jicvi** [gookit/validate#101]
example： Name	string `form:"name" json:"name" validate:"required"  errcode:"20003"  message:"is invalid"` 

errCode, errMsg = validate.Struct(users)

**Comment by inhere** [comment]
can custom validate tag:

```go
// GlobalOption settings for validate
type GlobalOption struct {
	// FilterTag name in the struct tags. default: filter
	FilterTag string
	// ValidateTag in the struct tags. default: validate
	ValidateTag string
}
```

please see https://github.com/gookit/validate#global-option
