### ISSUE TITLE
Int detected as float

### ISSUE THREAD

**Issue by nlandeker** [gookit/validate#105]
Hello,

I am not sure if this is my mistake but I have no idea what I am doing wrong.

I use `data, err := validate.FromJSONBytes(fiberContext.Body())` to bund JSON body to data.

I then `v := data.Create()`

And later use rule `v.StringRule("amount", "required|int|min:1")` to validate

in my JSON among other data there is 
```json
{
    "amount": 10,
...
}
```

No matter what the integer number I put in it gets detected as float and fails validation.

Do you have any idea what am I doing wrong?

**Comment by inhere** [comment]
The `encoding/json` always Unmarshal json numbers to go float.

so, you can Unmarshal json data to an struct, then call `validate.Struct()`

OR :

```go

v.FilterRule("amount", "int") // convert to int type
v.StringRule("amount", "required|int|min:1")
```

**Comment by nlandeker** [comment]
Thank you for explaining.
