### ISSUE TITLE
能不能加一个tag实现类似结构体Translates的功能

### ISSUE THREAD

**Issue by mygoodidea** [gookit/validate#110]
类似这样
```go
type UserForm struct {
	Name     string    `validate:"required|minLen:7" label:"姓名" message:"required:{field} 不能为空 | minLen:{field}最少7个字符"`
}
```

最后输出: 
`
姓名 不能为空
姓名 最少7个字符
`
这样比较简洁，Translates方法有点啰嗦，而且可以直接在控制器的参数定义匿名结构体

**Comment by inhere** [comment]
是支持的 https://github.com/gookit/validate/blob/master/README.zh-CN.md#%E9%AA%8C%E8%AF%81%E7%BB%93%E6%9E%84%E4%BD%93struct

结构体可以实现3个接口方法，方便做一些自定义：

- `ConfigValidation(v *Validation)` 将在创建验证器实例后调用
- `Messages() map[string]string` 可以自定义验证器错误消息
- `Translates() map[string]string` 可以自定义字段映射/翻译

![image](https://user-images.githubusercontent.com/5302062/140004847-b9d2972a-279a-47d9-85d5-8edd24784259.png)

**Comment by inhere** [comment]
你是说加 `label:"姓名"` 这个标签吗

**Comment by mygoodidea** [comment]
> 你是说加 `label:"姓名"` 这个标签吗

是的，比如我只想对`Name`字段配置个别名`姓名`，只需加个`label`标签，而不用每一个结构体添加一个`Translates`方法

**Comment by mygoodidea** [comment]
@inhere

**Comment by tomorrowsky** [comment]
有类似的需求，请问这个会加到需求列表里面吗？

**Comment by inhere** [comment]
可以的 ，最近找时间加上

**Comment by tomorrowsky** [comment]
期待
