### ISSUE TITLE
我看了一下，我有1个字段required，可以为""空，该怎么设置呢？

### ISSUE THREAD

**Issue by anyone0034** [gookit/validate#115]
我看文档中介绍的是 required | 字段为必填项，值不能为空，但是我有一个需求是字段必须存在，但可以为""，但是我使用""时，一直提示我required。

例如：我现在的struct是这样定义的，        Content    string     `json:"content"             validate:"required"        message:"required:内容必须填写"` 
如果content字段非空，验证通过。如果content=""空，提示需求required

**Comment by inhere** [comment]
那你写个 `validate:"string"` 就行，数据到了结构体，基础类型的字段肯定是存在的
