### ISSUE TITLE
希望自定义消息支持指针方法

### ISSUE THREAD

**Issue by dmskys** [gookit/validate#117]
希望支持指针方法，现在不支持指针方法
// Messages 您可以自定义验证器错误消息
func (f *UserForm) Messages() map[string]string {
	return validate.MS{
		"required": "oh! the {field} is required",
		"Name.required": "message for special field",
	}
}

// Translates 你可以自定义字段翻译
func (f *UserForm) Translates() map[string]string {
	return validate.MS{
		"Name": "用户名称",
		"Email": "用户Email",
		"ExtInfo.Homepage": "用户主页",
	}
}

**Comment by inhere** [comment]
??
