### ISSUE TITLE
如何在Create和Update中共用一套 验证规则

### ISSUE THREAD

**Issue by HuangeHei** [gookit/validate#12]
大佬又是我。。这次是在开发中遇到的问题，我现在是用验证规则绑定在了结构体的tag
这样创建是没有什么问题，但是在更新数据的时候会有问题，前端传递过来的更新数据 有些项不需要更新的话传的是空，还有些自定义的验证器是创建用的和更新的时候冲突的，这样一来数据的更新就没办法来验证。求教大佬有什么好的方式么？

**Comment by HuangeHei** [comment]
```
type User struct {
	ID uint `gorm:"primary_key;AUTO_INCREMENT;" json:"id" form:"id" validate:"-"`
	UserName string `gorm:"unique;not null" json:"user_name" form:"user_name" validate:"required|customValidator"`
	UserPasswd string `gorm:"not null" json:"-" form:"user_passwd" validate:"required"`	
}
```
这个自定义的customValidator 验证器 的验证规则 就会和 更新时 冲突

**Comment by inhere** [comment]
可以在创建验证时设置要验证的字段

https://github.com/gookit/validate/blob/eb25ea6e9da89e54f1fd51697c7903fc4b64f34d/validation_test.go#L486-L520

然后指定场景验证：

```go

	// on scene "create"
	ok := v.Validate("create")
```

**Comment by inhere** [comment]
@HuangeHei  是不是我上面说的这种使用场景呢？是否满足需要

**Comment by HuangeHei** [comment]
是这样的，因为一个字段创建的时候会有空值的检测，但是更新的时候是空值就代表了无更新，但是如果传值了，就得验证除了空值之外的验证规则。比如用户名 是否重复啊 这种。

**Comment by inhere** [comment]
好像没啥好办法 。。。 只有都不加required。 你有啥建议思路吗？

**Comment by aetherwu** [comment]
> 是这样的，因为一个字段创建的时候会有空值的检测，但是更新的时候是空值就代表了无更新，但是如果传值了，就得验证除了空值之外的验证规则。比如用户名 是否重复啊 这种。

这种场景似乎只能依赖于在 request 中验证，而在 struct 里面不设 require 限制。
但这种方法似乎多了一套配置文本。

**Comment by aetherwu** [comment]
我在想能否通过支持一种特别的标签来简化验证流程：比如，加入 requiredWhenCreate 场景？仅针对 struct。

问题可能在于如何鉴别“WhenCreate“。

我在 GROM 里面注意到它有自带的 NewRecord() 方法，可以返回此 entity 是否被创建的状态。但这种方法似乎存在不可控的外部依赖。

还有一种是要求开发者手动指定 ignore 特定的标签。比如，临时加入 Rules 让 validate 忽略 Password 字段上 required 标签。这个忽略操作，我不清楚当前类库是否支持。

只是一点想法。

**Comment by HuangeHei** [comment]
只有笨办法了~每种状态一套验证方式~
