### ISSUE TITLE
required int 会将0值当成empty，无法校验通过

### ISSUE THREAD

**Issue by chungang-li** [gookit/validate#123]
0值在业务中是正常的

**Comment by inhere** [comment]
`int 0` 的话，在go里是默认值 相当于空。

**Comment by chungang-li** [comment]
有没有解决办法呢 其他的方式？

**Comment by inhere** [comment]
业务逻辑避免使用 go 里面各个类型的默认值

**Comment by chungang-li** [comment]
> 业务逻辑避免使用 go 里面各个类型的默认值。 或者 不加 required, 使用 min 验证。

不使用required 会导致未上传该字段校验通过
