### ISSUE TITLE
Validate array/slice items

### ISSUE THREAD

**Issue by iarkaroy** [gookit/validate#124]
I may have missed something in the doc. I am wondering how I can validate each item in an array/slice.

Expected:

```go
m := map[string]interface{}{
    "names":  []string{"John", "Jane", "abc"},
}
v := validate.Map(m)
v.StringRule("names", "required|array|minLen:1")
v.StringRule("names.*", "string|minLen:4")
if v.Validate() {
    // ...
}
```

How can I achieve this?

**Comment by inhere** [comment]
:) Not currently supported...

**Comment by iarkaroy** [comment]
Any plan for such?

**Comment by inhere** [comment]
Yes, Planned. If I have time.

**Comment by inhere** [comment]
hi @iarkaroy 

This feature has been implemented in https://github.com/gookit/validate/releases/tag/v1.4.0

**Comment by iarkaroy** [comment]
> hi @iarkaroy
> 
> This feature has been implemented in https://github.com/gookit/validate/releases/tag/v1.4.0

Great. Thanks.
