### ISSUE TITLE
请问可否提供一些 Benchmark 相关的参数呢？

### ISSUE THREAD

**Issue by anxuanzi** [gookit/validate#134]
大佬您好，非常喜欢您的这个库，用起来真的非常顺手，我已经有很多项目在用您这个库啦。我这边有一个的新项目在决定使用哪种验证器。这边很关注的一个方向就是性能，可否给出一些压测的参数便于我们决定呢？

**Comment by inhere** [comment]
你好。
到现在为止，这个库基本上都是在完善功能，没有专门的做下性能优化。不过内置验证器都是在包级别加载缓存了的。

基本上所有功能强大的验证库都是用了反射的，要想特别好的性能估计不太现实。不过相对于你业务上使用io导致的性能消耗，验证器损耗的这点的性能都是能够接受的。

这里有一份之前其他人做的验证器压测报告：

 https://github.com/StrayDragon/benchmark-validate-go

**Comment by anxuanzi** [comment]
> 你好。 到现在为止，这个库基本上都是在完善功能，没有专门的做下性能优化。
> 
> > 不过内置验证器都是在包级别加载缓存了的，后期有时间再专门做下性能这块的优化。
> 
> 基本上所有功能强大的验证库都是用了反射的，要想特别好的性能估计不太现实。不过相对于你业务上使用io导致的性能消耗，验证器损耗的这点的性能都是能够接受的。
> 
> 这里有一份之前其他人做的验证器压测报告：
> 
> https://github.com/StrayDragon/benchmark-validate-go

感谢大佬的说明，建议可以把这个压测的信息放到 redme 里面，能够更好的供人参考。谢谢！

**Comment by inhere** [comment]
等我有时间做下这方面的优化，在做压测报告 :)
