### ISSUE TITLE
你好作者,请问能否帮忙查看一下全局添加验证器无效的问题

### ISSUE THREAD

**Issue by pya789** [gookit/validate#143]
```
package main

import (
	"fmt"

	"github.com/gookit/validate"
)

type Data struct {
	Name string `validate:"notNull"`
	Age  int    `validate:"required"`
}

func main() {
	validate.AddValidator("notNull", func(val any) bool {
		fmt.Println(val)
		return false
	})
	validate.AddGlobalMessages(map[string]string{
		"notNull": "不可为空",
	})
	v := validate.New(&Data{
		Name: "",
		Age:  18,
	})
	if !v.Validate() {
		fmt.Println(v.Errors.OneError())
	}
	fmt.Println("验证成功")
}
```

没有进入AddValidator的委托参数中 直接用validate包暴漏的函数调用都是无效的包括validate.Config()方法 
请问是否是我使用方法错误？
Go版本为1.18.1

**Comment by pya789** [comment]
另外使用Gin本身验证器时可以给字段类型定义为指针类型来判空，因为指针非空所以即便是0值，判断也是非空的。我刚才搜了issue里面有人提过这个问题，好像也是可以的，但是我设定了int指针 在gin把参数绑定为结构之后再调用验证器依然会判断为空，拉取项目源码调试后发现再进入ValueIsEmpty这个函数时val已经变成nil了，而不是指针地址0.0，请问有什么好的解决办法吗 感谢作者

**Comment by inhere** [comment]
```
v := validate.New(&Data{
		Name: "",
		Age:  18,
	})
```

`Name: ""` Name 是空值，不会调用验证器。 这样加 `validate:"required|notNull"` 有值才会调用验证器

**Comment by inhere** [comment]
你这里是想做什么样的验证呢？

**Comment by pya789** [comment]
> 你这里是想做什么样的验证呢？

想做初始值的非空验证...我刚才测试了一下你说的方法确实有效  但这样还是无法自定义非空验证了。。

**Comment by pya789** [comment]
> 你这里是想做什么样的验证呢？

```
type Menu struct {
	Type      *int   `json:"type" validate:"required"`
	ParentId  int    `json:"parentId" validate:"required"`
	Name      string `json:"name" validate:"required"`
	Path      string `json:"path" validate:"-"`
	PagePath  string `json:"pagePath" validate:"-"`
	Perms     string `json:"perms" validate:"-"`
	Icon      string `json:"icon" validate:"-"`
	Sort      int    `json:"sort" validate:"-"`
	KeepAlive int    `json:"keepAlive" validate:"-"`
	Status    int    `json:"status" validate:"-"`
}
```
比如这样 如果指针非nil就不为空 这样业务里可以把指针的值再解出来

**Comment by inhere** [comment]
> > 你这里是想做什么样的验证呢？
> 
> 想做初始值的非空验证...我刚才测试了一下你说的方法确实有效 但这样还是无法自定义非空验证了。。

初始值的非空验证 是指有默认值吗？

**Comment by inhere** [comment]
> 
> ```
> type Menu struct {
> 	Type      *int   `json:"type" validate:"required"`
> 	ParentId  int    `json:"parentId" validate:"required"`
> 	Name      string `json:"name" validate:"required"`
> 	Path      string `json:"path" validate:"-"`
> 	PagePath  string `json:"pagePath" validate:"-"`
> 	Perms     string `json:"perms" validate:"-"`
> 	Icon      string `json:"icon" validate:"-"`
> 	Sort      int    `json:"sort" validate:"-"`
> 	KeepAlive int    `json:"keepAlive" validate:"-"`
> 	Status    int    `json:"status" validate:"-"`
> }
> ```
> 
> 比如这样 如果指针非nil就不为空 这样业务里可以把指针的值再解出来

`*int` 使用指针也是可以的  validate:"required|notNull"`

**Comment by pya789** [comment]
> > > 你这里是想做什么样的验证呢？
> > 
> > 
> > 想做初始值的非空验证...我刚才测试了一下你说的方法确实有效 但这样还是无法自定义非空验证了。。
> 
> 初始值的非空验证 是指有默认值吗？

是的，参数有值和初始值相同 但是使用*int required还是会判断0为非空......

**Comment by pya789** [comment]
> > ```
> > type Menu struct {
> > 	Type      *int   `json:"type" validate:"required"`
> > 	ParentId  int    `json:"parentId" validate:"required"`
> > 	Name      string `json:"name" validate:"required"`
> > 	Path      string `json:"path" validate:"-"`
> > 	PagePath  string `json:"pagePath" validate:"-"`
> > 	Perms     string `json:"perms" validate:"-"`
> > 	Icon      string `json:"icon" validate:"-"`
> > 	Sort      int    `json:"sort" validate:"-"`
> > 	KeepAlive int    `json:"keepAlive" validate:"-"`
> > 	Status    int    `json:"status" validate:"-"`
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 比如这样 如果指针非nil就不为空 这样业务里可以把指针的值再解出来
> 
> `*int` 使用指针也是可以的 validate:"required|notNull"`

```
type Menu struct {
	Type      *int   `json:"type" validate:"required"`
	ParentId  int    `json:"parentId" validate:"required"`
	Name      string `json:"name" validate:"required"`
	Path      string `json:"path" validate:"-"`
	PagePath  string `json:"pagePath" validate:"-"`
	Perms     string `json:"perms" validate:"-"`
	Icon      string `json:"icon" validate:"-"`
	Sort      int    `json:"sort" validate:"-"`
	KeepAlive int    `json:"keepAlive" validate:"-"`
	Status    int    `json:"status" validate:"-"`
}
```
总之就是想实现 *int 这种指针类型的字段 只要指针非nil required对其判断非空 0 0

**Comment by inhere** [comment]
我测试一下

**Comment by pya789** [comment]
> 

好的辛苦作者了。

**Comment by pya789** [comment]
> 我测试一下
```
package main

import (
	"fmt"

	"github.com/gookit/validate"
)

type Data struct {
	Name string `validate:"required"`
	Age  *int   `validate:"required"`
}

func main() {
	age := 0
	v := validate.New(&Data{
		Name: "123",
		Age:  &age,
	})
	if !v.Validate() {
		fmt.Println(v.Errors.OneError())
		return
	}
	fmt.Println("验证成功")
}
```
这样的demo  按正常来说应该是输出验证成功 因为Data.Age是一个指针且不为nil 现在是反射取到值 最后还是走的0值判断...

**Comment by inhere** [comment]
我在本地改了 可以 

```go
type Data struct {
		Name string `validate:"required"`
		Age  *int   `json:"age" validate:"required"`
	}

	v := validate.New(&Data{
		Name: "tom",
		Age:  nil,
	})

	ok := v.Validate()
	assert.False(t, ok)
	assert.Equal(t, "age is required and not empty", v.Errors.One())

	// use ptr
	age := 0
	v = validate.New(&Data{
		Name: "tom",
		Age:  &age,
	})

	ok = v.Validate()
	assert.True(t, ok)
```

但是，使用指针值 就没法配合其他验证器了 比如 `min:10`

**Comment by pya789** [comment]
> 
```
package main

import (
	"fmt"

	"github.com/gookit/validate"
)

type Data struct {
	Name string `validate:"required"`
	Age  *int   `validate:"required"`
}

func main() {
	age := 10
	v := validate.New(&Data{
		Name: "123",
		Age:  &age,
	})
	ok := v.Validate()
	fmt.Printf("age:%d res:%v", age, ok)  // age:0 res:false // age:10 res:true
}
```
额 为啥我这个demo就不行

**Comment by inhere** [comment]
本地改动 还没提交的

**Comment by pya789** [comment]
> 本地改动 还没提交的

哦哦 期待更新

> 本地改动 还没提交的

辛苦作者了 ─=≡Σ(((つ•̀ω•́)つ

**Comment by pya789** [comment]
> > 本地改动 还没提交的
> 
> 哦哦 期待更新
> 
> > 本地改动 还没提交的
> 
> 辛苦作者了 ─=≡Σ(((つ•̀ω•́)つ

辛苦作者拉

**Comment by inhere** [comment]
可以拉 v1.4.2 测试下
