### ISSUE TITLE
Does required have to be used with min_len?

### ISSUE THREAD

**Issue by OscarVanL** [gookit/validate#161]
Hi,

I noticed in your examples you often use required|min_len, for example: 

```
Name     string    `validate:"required|min_len:7"
```

I was surprised to see this, because this is a primitive string, and the zero-value is "", which has length of 0. I thought the `min_len` rule would catch this anyway.

Is the required tag necessary on this rule?

**Comment by inhere** [comment]
if don't have `required` tag, on value is zero value(`0,nil,""`), will skip all validators

**Comment by OscarVanL** [comment]
I see, thank you.

By modifying the global settings I made this work as I intended :D 
```
	validate.Config(func(opt *validate.GlobalOption) {
		opt.StopOnError = false
		opt.SkipOnEmpty = false
		opt.CheckZero = true
	})
```
