### ISSUE TITLE
Allow single message that matches all validation rules

### ISSUE THREAD

**Issue by OscarVanL** [gookit/validate#163]
This is a feature request :) 

The library allows you to write custom messages that apply for each rule like this:

```
Age      int `validate:"required|int|min:1|max:99" message:"int:age must int|min:age min value is 1"`
```

However, in my case I would like to have the same validation error message for any validation rule for the field, because I do not want to reveal too much to the user about how I am validating:

```
Age      int `validate:"required|int|min:1|max:99" message:"*:Please check the Age value"`
```

Or maybe you could allow multiple rules to have the same message:
```
Age      int `validate:"required|int|min:1|max:99" message:"min,max:Please check the Age value|required:Please enter an age value"`
```

I thought maybe you could allow the `*` tag, where the message applies to every validation rule for the field, or allow comma-separated rule names.

**Comment by inhere** [comment]
On not set validator name:

```
Age      int `validate:"required|int|min:1|max:99" message:"Please check the Age value"`
```

will always return "Please check the Age value"

**Comment by OscarVanL** [comment]
Hmm, I have a field like this:

```
ID   string `json:"id" validate:"required|uuid4" message:"error-validation-internal"
```

with these global rules:
```
	newvalidate.Config(func(opt *newvalidate.GlobalOption) {
		opt.StopOnError = false
		opt.SkipOnEmpty = false
	})
```

And the result is:

```
validate.Errors(validate.Errors{"id":validate.MS{"required":"error-validation-internal", "uuid4":"id value should be a UUID4 string"},
```

So for the first rule (required), I get the custom name, but for the second rule (uuid4), I do not.

**Comment by OscarVanL** [comment]
I have attempted to make a fix @inhere, let me know what you think :) 

https://github.com/gookit/validate/pull/164

**Comment by inhere** [comment]
Thanks your PR #164. That's great 👍🏻

**Comment by OscarVanL** [comment]
Thank you! I eagerly await a release so I can use this fix in my codebase. Do you know when you next plan to release?

**Comment by inhere** [comment]
hi @OscarVanL  has been released the https://github.com/gookit/validate/releases/tag/v1.4.4

**Comment by OscarVanL** [comment]
Thank you! I will close this card :)
