### ISSUE TITLE
Nested struct with private field

### ISSUE THREAD

**Issue by desprit** [gookit/validate#179]
**System (please complete the following information):**

 - OS: `macOs`
 - GO Version: `1.18`
 - Pkg Version: `1.4.4` 

**Describe the bug**

Can't validate nested structs when it's unexportable.

**To Reproduce**

The following approach works:

```go
type StartDate struct {
	StartDate string `json:"start_date" validate:"required"`
}
type AvailabilityParameters struct {
	StartDate
}
```
If I don't provide a "start_date" value I will get `"start_date is required and not empty"`, perfect.

But having it this way:

```go
type availabilityParameters struct {
	StartDate string `json:"start_date" validate:"required"`
}
type AvailabilityParameters struct {
	availabilityParameters
}
var p *AvailabilityParameters
json.Unmarshal([]byte(`{}`), &p)
err := p.Validate()
```

I get `nil` error.

**Expected behavior**

I did it this way because I need unexportable fields and was basically following this advice:
https://stackoverflow.com/a/11129474/3459479

So my question is, can I do something to make Validate run validation on the nested struct?

**Comment by inhere** [comment]
Will skip unexportable fields in current logic.

https://github.com/gookit/validate/blob/ff2c8c36dbf49e40782a109582737b7ba284f686/data_source.go#L301-L306

**Comment by desprit** [comment]
@inhere Would you be interested in configuring it through config? Or there are underlying reasons to not do that?

**Comment by inhere** [comment]
add to TODO

**Comment by SharkFourSix** [comment]
> @inhere Would you be interested in configuring it through config? Or there are underlying reasons to not do that?
> 
> upd: I changed it on my side to not use private fields. Thank you for the quick answer.

You mean you made changes to your code?
--

Either way, I think this should be configurable. I just figured this out when I noticed validation was not catching the obvious and deliberate errors that I was typing. This is very dangerous because it gives off the impression that it works when it's not.
