### ISSUE TITLE
Second ValidateE does not work after using v.Reset()

### ISSUE THREAD

**Issue by OscarVanL** [gookit/validate#186]
**System (please complete the following information):**

 - OS: `MacOS `
 - GO Version: `1.19`
 - Pkg Version: `1.4.5`

**Describe the bug**

When using `v.Reset()` the second `ValidateE` on a struct does not return errors when it should.

**To Reproduce**

Go playground reproducible: https://go.dev/play/p/QMpNVu1KP7E

In this case my second validator scene "stuff" does not work if I use `v.Reset()`

```go
package main

import (
	"fmt"

	"github.com/gookit/validate"
)

func init() { // nolint:gochecknoinits
	validate.Config(func(opt *validate.GlobalOption) {
		opt.StopOnError = false
		opt.SkipOnEmpty = false
	})
}

type Settings struct {
	Id    string `validate:"required"`
	Kind  string `validate:"in:a,b"`
	Other string `validate:"min_len:10"`
}

func (Settings) ConfigValidation(v *validate.Validation) {
	v.WithScenes(validate.SValues{
		"metadata": []string{"Id", "Kind"},
		"stuff":    []string{"Other"},
	})
}

func main() {
	// Use same struct both times.
	s := Settings{
		Id:    "abc",
		Kind:  "a",
		Other: "foo",
	}

	fmt.Println("Starting case 1")

	// Failure mode: Two validator scenes used, the later validator scene's validation is not run despite v.Reset()
	v := validate.Struct(s)
	err := v.ValidateE("metadata")
	if err != nil {
		fmt.Println(err)
	}

	v.Reset()

	err = v.ValidateE("stuff")
	if err != nil {
		fmt.Println("Case 1: Expected behaviour!!")
	} else {
		fmt.Println("Case 1: DID NOT RUN CUSTOM VALIDATOR?!?")
	}

	fmt.Println("Starting case 2")

	// Workaround, instead of using v.Reset() I create a new validator for each scene, now the later validation works.
	v = validate.Struct(s)
	err = v.ValidateE("metadata")
	if err != nil {
		fmt.Println(err)
	}

	v = validate.Struct(s)

	err = v.ValidateE("stuff")
	if err != nil {
		fmt.Println("Case 2: Expected behaviour!!")
	} else {
		fmt.Println("Case 2: DID NOT RUN CUSTOM VALIDATOR?!?\n")
	}
}

```

**Expected behavior**

The same outcome should happen whether I use `v.Reset()` or create a new validator using `v.Struct(x)`.

**Comment by inhere** [comment]
`v.Reset()` Maybe there is some context data that is not reset

**Comment by OscarVanL** [comment]
With the debugger it looks like the `v.rules` and `v.validators` that were populated when we did `v.Struct()` are reset when we do `v.Reset()`, which means that no rules or validators exist anymore. 

I'm not sure if this is expected behaviour, I thought it would just reset previous results, not remove all the rules.
