### ISSUE TITLE
v1.4.6 change has broken existing behaviour

### ISSUE THREAD

**Issue by inhere** [gookit/validate#192]
**Regression**

This change has broken existing behaviour.

For eg: I have a JSON:

```json
{
  "main1": {
    "child11": 1,
    "child12": 2
  },
  "main2": {
    "child21": 5,
    "child22": 6
  }
}
```

Now, as per validation rules, key ```main1``` and ```main2``` are optional. And their respective children keys should be validated only when main key exists.

The validation rules are defined as:

```go
type Request struct {
	Main1 *struct {
		Child11     string `json:"child11" validate:"required"`
		Child12 string `json:"child12" validate:"required"`
	} `json:"main1"`
	Main2 *struct {
		Child21 string `json:"child21" validate:"required"`
		Child22 string `json:"child22" validate:"required"`
	} `json:"main2"`
}
```

Earlier, uptil **v1.4.5**, these definitions were working fine and children struct was validated only when the respective main key existed

Now, with the release **v1.4.6** , this behaviour does not work anymore as nil pointer check is removed.

_Originally posted by @madhurbhaiya in https://github.com/gookit/validate/issues/191#issuecomment-1373334318_

**Comment by lsh-0** [comment]
I thought I was going crazy! I'm new to `go` and `gookit` and have been trying to get 'child' fields of an embedded struct ignored for hours ... I've learnt quite a bit about `gookit` in the process but still, was getting very frustrated.

In my case I have:

```go
type SubConfig1 struct {
	Val int `validate:"required|min:1|max:65535"`
}

type SubConfig2 struct {
	Name string `validate:"required|in:foobar"`
}

type Config struct {
	Sub1 *SubConfig1
	Sub2 *SubConfig2
}
```

and then ignoring the other sub-config structs depending on what the user passes in:

```go
        user_command := "do2"
	idx := map[string]string{
		"Sub1": "do1",
		"Sub2": "do2",
	}
	for field_name, cmd := range idx {
		if user_command != cmd {
			v.AddRule(field_name, "safe")
		}
	}
```

I'm sure there is an easier way (that doesn't involve that `idx`), but in `1.4.6` this doesn't work and `1.4.5` it works as expected.

Thanks @inhere for saving my evening :)

**Comment by inhere** [comment]
hi @lsh-0 @madhurbhaiya @OscarVanL Add new validator `optional` for resolve this issue.

On struct, add `optional` on parent field, will be not validating sub-fields on parent is nil.

https://github.com/gookit/validate/blob/27b33f1bd5591e3471f8ec683f1fc6ee31ec4888/issues_test.go#L1267-L1306

**Comment by inhere** [comment]
Please upgrade to https://github.com/gookit/validate/releases/tag/v1.5.2
