### ISSUE TITLE
[Question] 是否有计划支持 protobuf 文件定义验证信息，生成代码？

### ISSUE THREAD

**Issue by shuqingzai** [gookit/validate#194]
如题，参考: https://github.com/bufbuild/protoc-gen-validate

支持在 Protobuf 文件中定义验证信息，在生成 go 代码时，同时生成验证信息文件

**Comment by inhere** [comment]
😄 我这没有这个的使用场景，不太清楚这个要怎么弄。
感觉这个需求应该新启动一个项目来做才好。

@shuqingzai  你有兴趣可以弄个项目，我可以提供一些我能提供的帮助。

**Comment by shuqingzai** [comment]
好的，谢谢你

**Comment by AGPDev** [comment]
> 好的，谢谢你

@shuqingzai See this: https://github.com/srikrsna/protoc-gen-gotag
