### ISSUE TITLE
email validate

### ISSUE THREAD

**Issue by shcabin** [gookit/validate#21]
1. 邮箱中最后为顶级域名，所以至少为两位字符，而且符合顶级域名规范
所以一下应该不匹配：
ab@a1wa.c_m
a@sina.c

2.  不能以dot结尾 ，例如： aaaa@qq.com.

3.  邮箱名似乎不能带#，但是我找不到相关规范

**Comment by inhere** [comment]
😄 我也是从网上找的匹配

**Comment by AllenX2018** [comment]
@inhere 尝试一下这个是否符合要求？ /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

**Comment by AllenX2018** [comment]
@inhere 可以直接开个写权限吗？我改完加完测试用例直接提交上去 : )

**Comment by inhere** [comment]
@AllenX2018  嗯，我开一下。😊 不过最好还是走PR，方便检查改动

**Comment by AllenX2018** [comment]
@inhere ok
