### ISSUE TITLE
panic occurs when passing nil

### ISSUE THREAD

**Issue by zKoz210** [gookit/validate#223]
**System (please complete the following information):**

 - OS: `macOS`
 - GO Version: `1.20`
 - Pkg Version: `1.5.0` ([master](https://github.com/gookit/validate/commit/18b0e03bb1d308fa89951ff0d9d949de871a0ce9))

**Describe the bug**

```
panic: reflect: call of reflect.Value.Interface on zero Value [recovered]
	panic: reflect: call of reflect.Value.Interface on zero Value
``

**Comment by inhere** [comment]
Can provide a example for this bug.

**Comment by zKoz210** [comment]
@inhere i make test https://github.com/gookit/validate/pull/224

**Comment by inhere** [comment]
hi @zKoz210 can use the latest code on master.

**Comment by zKoz210** [comment]
@inhere please check this test case https://github.com/gookit/validate/pull/225/files

**Comment by trapcodeio** [comment]
Am currently facing this bug, any idea when it was introduced?

**Comment by inhere** [comment]
hi @zKoz210 @trapcodeio bug fixed, will release on next version.

**Comment by inhere** [comment]
Please upgrade to https://github.com/gookit/validate/releases/tag/v1.5.2
