### ISSUE TITLE
能否请在文档中确认用法：可以为空，但有值必须满足条件。

### ISSUE THREAD

**Issue by aetherwu** [gookit/validate#24]
有的时候，一个值是可以为空的，代表不更新。但是一旦有值，则希望这个值是满足后续条件的。能否请详细指教这样的场景用法？（比如，现在版本不加required，就是满足这种需求的，但是以文本的方式在README里面加以确认，应该可以解除部分像我这样的困惑吧。）

谢谢。

**Comment by inhere** [comment]
不加 `required` 时，为空的就会跳过验证。
