### ISSUE TITLE
Pointer of UUID will break the Validate() function

### ISSUE THREAD

**Issue by jeremy-temelpa** [gookit/validate#247]
**System (please complete the following information):**

 - OS: `macOS`
 - GO Version: `1.20`
 - Pkg Version: `1.5.1`

**Describe the bug**

When the struct under validation contains a pointer of UUID, the Validate function will fail. With error msg

```
panic: reflect: call of reflect.Value.Len on zero Value [recovered]
	panic: reflect: call of reflect.Value.Len on zero Value
```

**To Reproduce**

```go
// go code
type TestUser struct {
	Name             string  `validate:"required|minLen:2|maxLen:100" filter:"trim|lower"`
	Email            string  `validate:"required|email" filter:"lower"`
	OptionalString   *string `validate:"required|minLen:2|maxLen:100" filter:"trimPtr|lowerPtr"`
	TestOptionalUUID *uuid.UUID // **Problem LINE**
}

func TestValidateStruct(t *testing.T) {
	t.Parallel()
	validation.RegisterValidationFilters()
	user := TestUser{
		Name:           "  John Doe  ",
		Email:          "JOHNDOE@EXAMPLE.COM",
		OptionalString: pointer.Ref("    Optional String   "),
	}

	err := validation.ValidateStruct(&user)

	// Check if there's an error and it's as expected
	if err != nil {
		t.Errorf("Validation failed: %v", err)
	}

	// Check if the filters were applied correctly
	if user.Name != "john doe" || user.Email != "johndoe@example.com" {
		t.Errorf("Filters not applied correctly. Got Name: %s, Email: %s", user.Name, user.Email)
	}

	if pointer.Deref(user.OptionalString) != "optional string" {
		t.Errorf("Filters not applied correctly. Got OptionalString: %s", *user.OptionalString)
	}
}

func trimPointerString(val interface{}) interface{} {
	if strPtr, ok := val.(*string); ok && strPtr != nil {
		trimmed := strings.TrimSpace(*strPtr)
		return &trimmed
	}
	return val
}

func lowerPointerString(val interface{}) interface{} {
	if strPtr, ok := val.(*string); ok && strPtr != nil {
		lowered := strings.ToLower(*strPtr)
		return &lowered
	}
	return val
}

func RegisterValidationFilters() {
	validate.AddFilter("trimPtr", trimPointerString)
	validate.AddFilter("lowerPtr", lowerPointerString)
}

func ValidateStruct[T any](input *T) error {
	if input == nil {
		return nil
	}
	v := validate.Struct(input)
	if v.Validate() {
		return nil
	} else {
		return errorx.New(v.Errors.Error())
	}
}

```

**Expected behavior**

Validate() should works fine without error

**Screenshots**

<img width="855" alt="image" src="https://github.com/gookit/validate/assets/127140506/c12b5174-44f7-4880-97fb-723fc91a4ad3">

**Comment by manicar2093** [comment]
Hi!. I was checking this and yes, this kind of validation does not work. I think this is due the nature of uuid google's package. Could this happend with other types based on Bytes?

**Comment by ip75** [comment]
yes. Validation fall in panic in recursive function.  https://go.dev/play/p/sfexq-rEVK9

**Comment by ip75** [comment]
> Hi!. I was checking this and yes, this kind of validation does not work. I think this is due the nature of uuid google's package. Could this happend with other types based on Bytes?

https://go.dev/play/p/fTVTY9roF3s - this test with github.com/gofrs/uuid package but result is the same. Bug is in validation code.

**Comment by ip75** [comment]
is there any workaround? I've to remove validation library from project because of this bug.

**Comment by inhere** [comment]
hi @ip75 @jeremy-temelpa The problem has been fixed, please wait for the next version to be released.

**Comment by inhere** [comment]
Please upgrade to https://github.com/gookit/validate/releases/tag/v1.5.2
