### ISSUE TITLE
能否有更明确的文档描述 contains/in 这些的用法？

### ISSUE THREAD

**Issue by aetherwu** [gookit/validate#25]
相对而言，=, >, <, =>, <=, 这些应该都比较直观。isXXX，required，这些也都很简洁直观。

但有些就不那么直观，比如:

validate="contains=[1,2,‘3’]"
validate="contains=1,2,3|..."
validate="in=(1,2,3)"
validate="range =1-2"
validate="range =3,4"
validate="range =(5,6)"
validate="range =[7,8]"

似乎都有可能。很多细节都有赖于开发者最初决定选用的方式。
但实际上合理的方式通常只有一种。

如果文档里可以直接写清楚范例，比大量的文字描述要更加直观清楚很多。

----
我斗胆猜一下，等下去试试……
validate="in:0,1,2"
看看会不会报错（捂脸

**Comment by inhere** [comment]
文档是写的比较简陋 有兴趣可以帮忙补下
