### ISSUE TITLE
验证图片失败!Failed to validate the image

### ISSUE THREAD

**Issue by pmxEr5lZwZ** [gookit/validate#27]
我上传一个照片  / i upload a photo.
<input type="file" name="thumbnail">

当我在BEEGO中获取文件 / when i get it in beego
f, _ , _ := this.GetFile(k)

并且创建一个validate规则 / and i create a validate rule
v.AddRule("thumbnail", "image")

控制台提示debug信息：thumbnail must be an uploaded image file
The console debug information:  thumbnail must be an uploaded image file

**Comment by inhere** [comment]
你是怎么创建验证实例的？

**Comment by pmxEr5lZwZ** [comment]
验证实例创建的没问题，因为我试了一下其他文字类的字段，如required,Minlen等，都能正常提示，唯独image这个有问题

**Comment by pmxEr5lZwZ** [comment]
```
func (this *Post) Store() {
	m := this.Ctx.Request.MultipartForm
	tmp := make(map[string]interface{})
	//Form Field
	for k, v := range m.Value{
		i, err := strconv.Atoi(v[0])
		if err != nil {
			tmp[k] = v[0]
		}else {
			tmp[k] = i
		}
	}
	//Form File
	for k, _ := range m.File{
		f, _ , _ := this.GetFile(k)
		tmp[k] = f
		logs.Debug(f)
	}
	logs.Debug(tmp)
	v := validate.Map(tmp)

	cms2.ContentPostStore(v)

	if v.Validate() {
		logs.Debug("5555555555555555555555")
	}else{
		logs.Debug(v.Errors)
		logs.Debug("666666666666666666666666")
	}
```


```
func ContentPostStore(v *validate.Validation) {
	v.AddRule("thumbnail", "image")
}
```

**Comment by inhere** [comment]
上传文件验证现在是基于 Request 对象创建的一个 Form实例，传map 不会验证上传文件 :)。

你可以直接 `v := validate.Request(http.Request)` 创建实例，会自动收集上传文件信息。

再：

```go
v.AddRule("thumbnail", "image")
```
