### ISSUE TITLE
uint 为 0 时无法验证最小值

### ISSUE THREAD

**Issue by Git-So** [gookit/validate#3]
结构体如下：
```go
type Tag struct {
	ID   uint   `validate:"min:2"`
	Name string `validate:"required|maxLen:20"`
}
```

`Tag.ID = 0`   验证通过，有问题

`Tag.ID = 1`   验证不通过，这是对的

@inhere

**Comment by inhere** [comment]
uint 0 的话，在go里是默认值 相当于空了,就不会去验证...

**Comment by inhere** [comment]
你在前面加上 `required` 就会验证为空了

**Comment by Git-So** [comment]
> 在你前面加上`required`就会验证为空了

谢谢，我是这样处理的
