### ISSUE TITLE
奇怪的返回值，年龄最少18岁%!(EXTRA int64=18)

### ISSUE THREAD

**Issue by MarcoBeer** [gookit/validate#36]
提交的数据是 
`age=10 ` 
www.xxx.com/test?age=10

结构体里定义的是 
`Age int `form:"age" json:"age" validate:"required|int|min:18|max:150"``

自定义返回的信息是 

`return validate.MS{
		
		"Age.min":"年龄最少18岁",
		"Age.max":"年龄最大150岁",
	}
`

实际上返回的错误信息是
`年龄最少18岁%!(EXTRA int64=18)`
不知道为什么突然会冒出来 %!(EXTRA int64=18)
为什么会突然冒出来这样的？

**Comment by inhere** [comment]
版本呢

**Comment by MarcoBeer** [comment]
> 多少版本呢

module github.com/gookit/validate

go 1.11

require (
	github.com/gookit/filter v1.1.0
	github.com/gookit/goutil v0.2.4
	github.com/stretchr/testify v1.3.0
)

应该是1.11这个版本，今天导入的这个包

**Comment by inhere** [comment]
能贴一下你的代码吗，我测试运行下

**Comment by MarcoBeer** [comment]
`package controllers
import(
	"github.com/astaxie/beego"
	"fmt"
	"github.com/gookit/validate"
)

type UserController struct{
	beego.Controller
}


/**
 * 用户信息的验证器
 *
 */





type UserForm struct{
	
	Name string `form:"username" json:"name" validate:"required|minLen:7"`
	Email string `form:"email" json:"email" validate:"email"`
	Age int `form:"age" validate:"required|int|min:18|max:150" json:"age"`

}


type Result struct{
	Status int `json:"status"`
	Msg interface{} `json:"msg"`
	Data interface{} `json:"data"`
}




func (f UserForm) Messages() map[string]string {
	return validate.MS{
		"required": "{field}不能为空",
		"Name.minLen":"用户名最少7位",
		"Name.required": "用户名不能为空",
		"Email.email":"邮箱格式不正确",
		"Age.min":"年龄最少18岁",
		"Age.max":"年龄最大150岁",
	}
}

func (f UserForm) Translates() map[string]string {
	return validate.MS{
		"Name": "用户名",
		"Email": "邮箱",
		"Age":"年龄",
	}
}



func (c *UserController) Get(){
    u:=UserForm{}
    

	if err:=c.ParseForm(&u); err!=nil {
        fmt.Println("接收数据出错了")
        
        c.Data["json"]=Result{0,"提交数据失败，请检查重试",nil}
        c.ServeJSON()
     
     }else{

          fmt.Println(u.Name)
          fmt.Println(u.Age)
          fmt.Println(u.Email)

//验证数据
	     
        
	     v := validate.Struct(&u)

        if v.Validate() { // validate ok
			fmt.Println("form data validate is ok")
			
			c.Data["json"]=Result{1,"添加用户成功",u}
		    c.ServeJSON()

		} else {
			// fmt.Println(v.Errors) // all error messages
			fmt.Println(v.Errors.One()) // returns a random error message text
			// fmt.Println(v.Errors.Field("Name")) // returns error messages of the field 
		     c.Data["json"]=Result{0,v.Errors.One(),u}
		     c.ServeJSON()
		}
		
		

    }

	
	

}
`
我这个是beego框架里的代码，请查看

**Comment by MarcoBeer** [comment]
> 能贴一下你的代码吗，我测试运行下

package controllers
import(
	"github.com/astaxie/beego"
	"fmt"
	"github.com/gookit/validate"
)

type UserController struct{
	beego.Controller
}


/**
 * 用户信息的验证器
 *
 */





type UserForm struct{
	
	Name string `form:"username" json:"name" validate:"required|minLen:7"`
	Email string `form:"email" json:"email" validate:"email"`
	Age int `form:"age" validate:"required|int|min:18|max:150" json:"age"`

}


type Result struct{
	Status int `json:"status"`
	Msg interface{} `json:"msg"`
	Data interface{} `json:"data"`
}




func (f UserForm) Messages() map[string]string {
	return validate.MS{
		"required": "{field}不能为空",
		"Name.minLen":"用户名最少7位",
		"Name.required": "用户名不能为空",
		"Email.email":"邮箱格式不正确",
		"Age.min":"年龄最少18岁",
		"Age.max":"年龄最大150岁",
	}
}

func (f UserForm) Translates() map[string]string {
	return validate.MS{
		"Name": "用户名",
		"Email": "邮箱",
		"Age":"年龄",
	}
}



func (c *UserController) Get(){
    u:=UserForm{}
    

	if err:=c.ParseForm(&u); err!=nil {
        fmt.Println("接收数据出错了")
        
        c.Data["json"]=Result{0,"提交数据失败，请检查重试",nil}
        c.ServeJSON()
     
     }else{

          fmt.Println(u.Name)
          fmt.Println(u.Age)
          fmt.Println(u.Email)

//验证数据
	     
        
	     v := validate.Struct(&u)

        if v.Validate() { // validate ok
			fmt.Println("form data validate is ok")
			
			c.Data["json"]=Result{1,"添加用户成功",u}
		    c.ServeJSON()

		} else {
			// fmt.Println(v.Errors) // all error messages
			fmt.Println(v.Errors.One()) // returns a random error message text
			// fmt.Println(v.Errors.Field("Name")) // returns error messages of the field 
		     c.Data["json"]=Result{0,v.Errors.One(),u}
		     c.ServeJSON()
		}
		
		

    }

	
	

}

**Comment by inhere** [comment]
@MarcoBeer 感谢提交问题。 

找到一个问题 `年龄最少18岁` 你设置了固定的消息，我底层仍然按有参数时的 调用了 Sprintf()，导致多了后面的一段。 已经修复，稍后发布新的版本。

**Comment by MarcoBeer** [comment]
> @MarcoBeer 感谢提交问题。
> 
> 找到一个问题 `年龄最少18岁` 你设置了固定的消息，我底层仍然按有参数时的 调用了 Sprintf()，导致多了后面的一段。 已经修复，稍后发布新的版本。

好的，谢谢作者

**Comment by MarcoBeer** [comment]
> @MarcoBeer 感谢提交问题。
> 
> 找到一个问题 `年龄最少18岁` 你设置了固定的消息，我底层仍然按有参数时的 调用了 Sprintf()，导致多了后面的一段。 已经修复，稍后发布新的版本。

请问作者，已经发布了吗？

**Comment by inhere** [comment]
还没有的，估计要稍后还有两个小问题解决了一起发。

你把消息设置这 `"Age.min":"年龄最少18岁",` 改成 `"Age.min":"年龄最少%d岁",` 也可以避免这个问题

**Comment by MarcoBeer** [comment]
> 还没有的，估计要稍后还有两个小问题解决了一起发。
> 
> 你把消息设置这 `"Age.min":"年龄最少18岁",` 改成 `"Age.min":"年龄最少%d岁",` 也可以避免这个问题

好的，感谢作者
