### ISSUE TITLE
怎么设置正则表达式验证

### ISSUE THREAD

**Issue by MarcoBeer** [gookit/validate#37]
作者您好
看代码是有正则表达式验证的regexp 
但是具体怎么使用可以给一个例子吗？
感激不尽

例如 Age字段只能为1-3位数字 \d{1-3}
在结构体里定义验证规则的时候，应该怎么定义呢？

**Comment by inhere** [comment]
@MarcoBeer regexp 是用于string验证的。1-3位数字可以直接 `min:1|max:100`

给个stract使用正则的示例：

```go
	type regForm struct {
		Age string `validate:"regex:^\\d{1,3}$"`
	}

	f1 := regForm{"12"}
	v = validate.Struct(&f1)
	ok = v.Validate() // True

	f1 = regForm{"1200"}
	v = Struct(&f1)
	ok = v.Validate() // False
```

**Comment by MarcoBeer** [comment]
谢谢作者，感激不尽

**Comment by MarcoBeer** [comment]
> @MarcoBeer regexp 是用于string验证的。
> 
> 检查1-3位age数字可以直接 `min:1|max:100` 或者 `between:1,100`
> 
> 列一个stract使用正则的示例：
> 
> ```go
> 	type regForm struct {
> 		Age string `validate:"regex:^\\d{1,3}$"`
> 	}
> 
> 	f1 := regForm{"12"}
> 	v = validate.Struct(&f1)
> 	ok = v.Validate() // True
> 
> 	f1 = regForm{"1200"}
> 	v = Struct(&f1)
> 	ok = v.Validate() // False
> ```

谢谢作者，感激不尽
