### ISSUE TITLE
maxLength 对中文不友好吗?

### ISSUE THREAD

**Issue by lihaotian0607** [gookit/validate#39]
maxLength 设置为10 结果传6个汉字就无法通过了!

**Comment by AllenX2018** [comment]
@inhere 您好~请问一下 maxLength 指的是字符个数长度还是字符编码长度？

**Comment by inhere** [comment]
@AllenX2018  :) 这里很简单，直接用的 len("string") 算长度

**Comment by AllenX2018** [comment]
@inhere 那是否可以用 str :=[]rune("string"),  len (str) 算出长度？

**Comment by inhere** [comment]
可以的。

**Comment by inhere** [comment]
已经调整了

https://github.com/gookit/validate/commit/78a5e85b449c6e857b11b25be5a1a615db653483

**Comment by AllenX2018** [comment]
@inhere 哥们~你的办事效率好快！！我看你们开源几个包都挺不错的，有时间、有机会的话，可以和你们一起参与贡献、维护？

**Comment by inhere** [comment]
@AllenX2018  欢迎欢迎!

刚刚这个主要是修改很简单，所以直接改了。 哈哈

:( 主要就我一个人弄，有空闲时间弄下。有兴趣参与非常欢迎！！ 可以加我微信 inhereat

**Comment by AllenX2018** [comment]
@inhere 好咧，对呀~我也想这样想的

**Comment by AllenX2018** [comment]
@inhere 那你太厉害了，一个人贡献那么多，而且还是空余时间搞得，可以！！！

**Comment by inhere** [comment]
@AllenX2018 github 上邀请你了，你到组织页应该能看到 或者 邮箱里

**Comment by AllenX2018** [comment]
@inhere 好的，感谢~

**Comment by Kisesy** [comment]
为什么不用 utf8.RuneCountInString 计数

**Comment by inhere** [comment]
😄
