### ISSUE TITLE
data_source.go  第 327 行的 Set() 方法

### ISSUE THREAD

**Issue by fumeboy** [gookit/validate#40]
Set(field string, val interface{})

参数分别是 “Msg2”（string），“ping”（string）

在 355 行，`newVal, err = convertType(val, srcKind, fv.Kind())`
返回的 newVal 和 err 均为 nil

因为 err 为 nil
接下来的 
```
if err != nil {
	return nil, err
}
```
没有生效

导致 361 行的` fv.Set(reflect.ValueOf(newVal)) `接收的参数 newVal 以 nil 传入

这里直接 panic，而且也没有错误处理

请问，Set()方法有什么作用？为了解决刚才我遇到的这个问题，我让 set（）方法直接返回了 参数中传入的 val

**Comment by fumeboy** [comment]
补充：

`func (d *StructData) Set`中 d 的值是 {"FilterTag":"filter","ValidateTag":"validate"}

**Comment by inhere** [comment]
`Set()` 大部分情况下都是直接返回 输入的 val
仅当应用了 filter 或者其他情况 导致值/值类型 变化，就会更新原来的字段值

**Comment by inhere** [comment]
@fumeboy  为啥关了？不是有问题吗

**Comment by fumeboy** [comment]
问题发生在：使用自定义filter将 *string 转化为 string ，以使用 minlen 等字符串验证器

**Comment by inhere** [comment]
看下现在的版本还有问题没
