### ISSUE TITLE
全局自定义的验证器，怎样加上自定义的错误信息

### ISSUE THREAD

**Issue by WilliamYang1992** [gookit/validate#41]
我看了文档代码，好像没有地方可以添加自定义的错误消息

**Comment by inhere** [comment]
提供了方法的

https://github.com/gookit/validate/blob/add009e9c2a9a9955f68571e5de5a6b7b5e94808/validation.go#L410-L424

**Comment by WilliamYang1992** [comment]
@inhere Hi, 你好，谢谢你的信息，我已经正确用上了

另外，我希望可以不用在每个validation 重复添加 withMessages 方法，一开始就添加时就可以指定自定义的消息，例如下面这样

`func AddValidator(name string, checkFunc interface{}, message string) {
	fv := checkValidatorFunc(name, checkFunc)

	validators[name] = 2 // custom
	validatorValues[name] = fv
	validatorMetas[name] = newFuncMeta(name, false, fv)
	builtinMessages[name] = message
}`

**Comment by inhere** [comment]
en 我下个小版本加上
