### ISSUE TITLE
TODO 请问有方法实现结构体的嵌套嘛

### ISSUE THREAD

**Issue by Mrliu8023** [gookit/validate#42]
在使用protobuf的时候，起先定义了一个User，在User里面定义了字段和校验，然后在请求的message中直接`message UserNewReq {User user = 1;}`,这时候好像没有去校验字段。

**Comment by inhere** [comment]
暂时没有支持 :(

**Comment by fishyww** [comment]
我尝试增强这个功能

**Comment by inhere** [comment]
可以的 @fishyww
