### ISSUE TITLE
当值为int 0时required会提示验证错误

### ISSUE THREAD

**Issue by Barrett-M82A1** [gookit/validate#50]
```
type AddMenuRequest struct {
	ParentId  int64  `json:"parent_id"  validate:"required|uint" message:"required:父级ID不能为空|uint:父级ID参数异常"`
}
```
当字段必填并且可以为0时就不能这么使用验证了，它会告诉我这个字段的值为空。
我只能验证uint，再在别的地方另外去判断到底有没有传parent_id这个字段

**Comment by AllenX2018** [comment]
https://github.com/gookit/validate/blob/36d054a88f9f148ffdbbf05d01294537f2c7592b/helper.go#L557-L596

从源码看，输入校验的 V 值 == 基础类型默认值的话，都会出现这样的错误。
有好的解决方案吗？ @inhere

**Comment by inhere** [comment]
在结构体上面是没办法的，一初始化就有默认值了。

**Comment by inhere** [comment]
要么先直接验证map，这样可以检查大字段是否存在。 验证后在绑定到结构体

**Comment by Barrett-M82A1** [comment]
是的目前看来只好分两步验证了，不过业务上类似的场景也不多，感谢您的回复
