### ISSUE TITLE
regexp 无法匹配

### ISSUE THREAD

**Issue by kirinse** [gookit/validate#6]
类似这样的正则应该如何在 struct 中书写规则?

```^(SLOTS|LIVE|SPORTS|LOTTERY)(,(SLOTS|LIVE|SPORTS|LOTTERY))*$```

参数会用 | 分隔，跟踪得到匹配规则变为 ```^(SLOTS```

如果改为
```^(SLOTS\|LIVE\|SPORTS\|LOTTERY)(,(SLOTS\|LIVE\|SPORTS\|LOTTERY))*$ ```
则该条规则丢失

plus: 正则表达式如有 ```,``` 也会导致规则丢失

**Comment by inhere** [comment]
😄 哈哈 这没办法，struct里必须用两个字符来分割验证器和参数，跟这两个字符冲突的参数都可能有问题。

像你这样对一些字段特殊验证的，可以在这个struct添加自定义验证器来对这个字段值验证。

> README 上有简单的示例

```go
// UserForm struct
type UserForm struct {
	Code     string    `validate:"customValidator"` // 使用自定义验证器
}

// CustomValidator 定义在结构体中的自定义验证器
func (f UserForm) CustomValidator(val string) bool {
	return len(val) == 4
}
```

**Comment by kirinse** [comment]
最终采用了 v.AddRule() 来添加验证规则 :)

**Comment by inhere** [comment]
使用 `v.AddRule()` 确实更快 😄
