### ISSUE TITLE
请问支持一个struct动态添加验证规则吗？

### ISSUE THREAD

**Issue by dmskys** [gookit/validate#62]
由于我的struct是由idl生成的无法进行改变添加验证规则，是进行反解析后会赋值给这个结构体，然后我想在这个结构体上进行添加字段验证，提示。

**Comment by dmskys** [comment]
我希望跟map一样进行动态的添加字段和错误消息提示

**Comment by inhere** [comment]
手动添加规则都可以的。

**Comment by inhere** [comment]
refer #42
