### ISSUE TITLE
 Cache field information？

### ISSUE THREAD

**Issue by fishyww** [gookit/validate#68]
下面两个方法都需要用到``fv := d.value.FieldByName(field)``,是否考虑加个缓存？
https://github.com/gookit/validate/blob/a8515f864db585e339bb8cbda3d435e733f28ac4/data_source.go#L371
https://github.com/gookit/validate/blob/a8515f864db585e339bb8cbda3d435e733f28ac4/data_source.go#L421

**Comment by inhere** [comment]
可以的。 👍

**Comment by fishyww** [comment]
优化这一块代码会涉及我之前提的那个结构嵌套的代码，你reviewy一下代码，不通过的就是close掉就行了，这样我好优化这一块的代码。

**Comment by inhere** [comment]
稍后我合并下。我再调整下看看
