### ISSUE TITLE
[]string 怎么检测 string的长度

### ISSUE THREAD

**Issue by chenzhigang9521** [gookit/validate#75]
[]string{"12434", "abdcg"}

我想检测slice中值的长度，该怎么做

**Comment by inhere** [comment]
内置的暂时不支持这样检查。

你这可以加个自定义验证器检查下

**Comment by chenzhigang9521** [comment]
> 内置的暂时不支持这样检查。
> 
> 你这可以加个自定义验证器检查下

嗯嗯，好的，谢谢
