### ISSUE TITLE
required_if 不能指定bool类型字段的值 检测

### ISSUE THREAD

**Issue by chenzhigang9521** [gookit/validate#76]
validate 使用required_if 想让某个字段在一个字段为false的时候必填 这种情况下检测不出来

**Comment by inhere** [comment]
能给个测试用例吗

**Comment by chenzhigang9521** [comment]
> 能给个测试用例吗

![image](https://user-images.githubusercontent.com/25320051/103989266-68e4c980-51ca-11eb-8f88-68138f117b89.png)

IsPrivate             bool           `json:"is_private"`
Categories            []*CategoryReq `json:"categories" validate:"required_if:is_private,false"`

**Comment by inhere** [comment]
`v1.3.1` 修复了。 

"required_if:is_private,false" 要写成 "required_if:IsPrivate,false" 内部才能取到 struct.IsPrivate 的值做判断。
