### ISSUE TITLE
无法自定义require_if检测方法

### ISSUE THREAD

**Issue by chenzhigang9521** [gookit/validate#77]

**Comment by chenzhigang9521** [comment]
因为require_if无法检测bool类型，需要自定义，自定义后是不能生效的

**Comment by inhere** [comment]
可以换个名字。 比如 `require_if2`

**Comment by chenzhigang9521** [comment]
> 可以换个名字。 比如 `require_if2`

换个名字是指什么？辛苦在说详细一些

**Comment by chenzhigang9521** [comment]
> 可以换个名字。 比如 `require_if2`
您好，我的问题可能没说清楚，补充一下

![image](https://user-images.githubusercontent.com/25320051/103990120-adbd3000-51cb-11eb-89cd-0f7ae54a2f27.png)

这块会把false当作空值处理了，如果不是空值的话就会进行required_if判断了

**Comment by inhere** [comment]
```
IsPrivate bool json:"is_private"
Categories []*CategoryReq json:"categories" validate:"required_if:is_private,false"
``

不覆盖定义 `required_if`，定义一个新的验证器 `require_if2`, 使用新的：

```
IsPrivate bool json:"is_private"
Categories []*CategoryReq json:"categories" validate:"required_if2:is_private,false"
``

**Comment by chenzhigang9521** [comment]
> ```
> IsPrivate bool json:"is_private"
> Categories []*CategoryReq json:"categories" validate:"required_if:is_private,false"
> ```
> 
> 不覆盖定义 `required_if`，定义一个新的验证器 `require_if2`, 使用新的：
> 
> ```
> IsPrivate bool json:"is_private"
> Categories []*CategoryReq json:"categories" validate:"required_if2:is_private,false"
> ```

我定义新的了，是这样的

**Comment by chenzhigang9521** [comment]
> ```
> IsPrivate bool json:"is_private"
> Categories []*CategoryReq json:"categories" validate:"required_if:is_private,false"
> ```
> 
> 不覆盖定义 `required_if`，定义一个新的验证器 `require_if2`, 使用新的：
> 
> ```
> IsPrivate bool json:"is_private"
> Categories []*CategoryReq json:"categories" validate:"required_if2:is_private,false"
> ```

您好，您说的定义新的验证器是指自定义检测方法么

**Comment by AllenX2018** [comment]
基础数据类型都有这样的问题，例如int的默认值是0，bool的默认值是false，如果你填写的值刚好是默认值，就会出现这样的问题，可以贴一下你的代码吗？我们尝试去解决这个问题。

**Comment by chenzhigang9521** [comment]
> 基础数据类型都有这样的问题，例如int的默认值是0，bool的默认值是false，如果你填写的值刚好是默认值，就会出现这样的问题，可以贴一下你的代码吗？我们尝试去解决这个问题。

您好，我这边代码不太好粘，就给您一个例子，您看看行么
type CreateArticleReq struct {
	IsPrivate             bool           `json:"is_private"`
	Cover                 string         `json:"cover" validate:"required_if:IsPrivate,false"`
}
传参时，is_private=false

**Comment by AllenX2018** [comment]
ok，大致明白，不单是bool >false,其他基础数据类型默认值都会出现这样的问题，你可以试一下int > 0，问题都会复现

**Comment by chenzhigang9521** [comment]
> ok，大致明白，不单是bool >false,其他基础数据类型默认值都会出现这样的问题，你可以试一下int > 0，问题都会复现

嗯嗯，是的，如果可以自定义required的方法的话也能解决这个问题，可是不能自定义

**Comment by AllenX2018** [comment]
字段用指针试一下

**Comment by chenzhigang9521** [comment]
> 字段用指针试一下

嗯嗯，试了下，用指针可以解决的，谢谢

**Comment by AllenX2018** [comment]
不客气，感谢你的反馈！

**Comment by inhere** [comment]
refer https://github.com/gookit/validate/issues/76
v1.3.1 特殊处理了这里bool值的判断，可以支持这样检查了


> > 可以换个名字。 比如 `require_if2`
> > 您好，我的问题可能没说清楚，补充一下
> 
> ![image](https://user-images.githubusercontent.com/25320051/103990120-adbd3000-51cb-11eb-89cd-0f7ae54a2f27.png)
> 
> 这块会把false当作空值处理了，如果不是空值的话就会进行required_if判断了
