### ISSUE TITLE
How to apply filter via struct?

### ISSUE THREAD

**Issue by jacekk** [gookit/validate#8]
https://github.com/gookit/validate/blob/master/validation_test.go#L126 - this is a nice way to apply validators into specific struct property. Is there a way to apply filters at the same line?

I've tried:

```go
type Whatever struct {
	Uno    string `validate:"required|lower|in:one,two,true" `             // --> validate: the validator 'lower' is not exists
	Dos    string `validate:"required|upper|enum:FOUR,FIVE,SIX" `          // --> validate: the validator 'upper' is not exists
	Tres   string `filter:"upper" validate:"required|in:ONE,TWO,THREE" `   // passing 'one' --> Tres value must be in the enum [ONE TWO THREE]
	Cuatro string `filter:"lower" validate:"required|enum:four,five,six" ` // passing 'SiX' --> Cuatro value must be in the enum [four five six]
}
```

but without success. Adding `validation.FilterRule("Tres", "trim|upper")` works, but it is somehow distant from those validation rules (within a struct). I would like to keep those together. Can you update the Readme. Or at least provide some examples in here?

**Comment by inhere** [comment]
Sorry，The filter tag function has not been implemented in the struct yet.

**Comment by inhere** [comment]
hi @jacekk , will add filter tag support on struct.

https://github.com/gookit/validate/blob/0bc571fa32e4524a17dc3c6882fe79f6b8f653c3/filtering_test.go#L11-L33

**Comment by inhere** [comment]
@jacekk  Can I close this issues?

**Comment by jacekk** [comment]
@inhere I've seen that it was added into tests, so I assume it works properly and might be closed. I will test this weekend, though.

**Comment by inhere** [comment]
ok. 😄  Please pull "1.1.0" or "master" to use

**Comment by jacekk** [comment]
Works great ... at least with strings and `trim` and `lower` filters. Thx :)
