### ISSUE TITLE
自定义字段验证如何添加错误信息

### ISSUE THREAD

**Issue by HuangeHei** [gookit/validate#9]
1.自定义的字段验证中，如果验证不通过如何返回错误信息
2.如何开启中文返回信息

**Comment by inhere** [comment]
1. 自定义的字段验证中，如果验证不通过如何返回错误信息

> `自定义的字段验证` 是指添加了自定义的验证器吗？ 
是的话，你往validation实例里 `AddMessage(key, msg string)` 即可。 key 是你的验证器名字

2. 如何开启中文返回信息

> 可以参考 https://github.com/gookit/validate/blob/master/locales/locales_test.go
注册加载一个新的语言数据，就会覆盖默认的错误信息

**Comment by HuangeHei** [comment]
谢谢大佬  大晚上的回复我，第2个问题解决了，但是第1个问题还是有些疑问。

1.对的 第一个是验证结构体时 自定义的验证器，但是我刚刚试了 只有validation实例只有AddMessages
`v := validate.Struct(u)					// 创建验证实例
v.AddMessages(map[string]string{"CustomValidator":"重复，不是唯一"})  // 添加msg


func (f User) CustomValidator(val string) bool {  // 试了一下 验证器 正常工作了
	var u []User
	db.Where("user_name = ?",val).Find(&u)
	fmt.Println("CustomValidator:",u)
	if len(u) <= 0 {
		return true
	}else{
		return false
	}
}

`

**Comment by inhere** [comment]
😄  不好意思！ `v` 没有直接暴露 `AddMessage`，可以这样

```go
v.Trans().AddMessage("custom", "message0")
```

不过直接给实例添加消息，估计在使用上不太方便。

你可以给结构体添加一个方法，可以对当前结构体验证时起效:

```go
// Messages you can custom define validator error messages.
func (f User) Messages() map[string]string {
	return validate.MS{
		"required":      "oh! the {field} is required",
		"Name.required": "message for special field",
        "CustomValidator": "OO，出错啦！！",
	}
}
```

可以参考README里的示例或者单元测试里。

结构体可以实现3个接口方法，方便做一些自定义：

- `ConfigValidation(v *Validation)` 将在创建验证器实例后调用
- `Messages() map[string]string` 可以自定义验证器错误消息
- `Translates() map[string]string` 可以自定义字段翻译

**Comment by HuangeHei** [comment]
谢谢~问题解决啦~

**Comment by inhere** [comment]
ok. 有啥问题或者建议可以提出来。更欢迎提PR 😀
