### ISSUE TITLE
FromRequest 使用疑问？

### ISSUE THREAD

**Issue by NeroCho** [gookit/validate#91]
```
// 定义struct 验证 的 demo
type DemoRequest struct {
	UserName  string `json:"userName" validate:"required|minLen:2|maxLen:7"`
	Phone     string `json:"phone" validate:"required|len:11"`
}

u := &DemoRequest{
...
}

v := validate.Struct(u)


// FromRequest 的demo
data, err := validate.FromRequest(r)
if err != nil {
   panic(err)
}

v := data.Create()
// setting rules
v.FilterRule("age", "int") // convert value to int
v.AddRule("name", "required")
...

if v.Validate() { // validate ok
```

 这里我有个疑问，我在使用FromRequest时，没找到使用struct验证的例子（不知道是不是太菜了。。。）
 既然我都已经定义了struct就不用再用dataFace来一遍吧。。。
```
//建议
//可以多加一个参数 如下：
validate.FromRequest(httpRequest,struct)  //有点像gin的shouldBindJson，不过gin的validator和作者的差的有点远。。。

// 也可以再dataface中添加对应拓展
```

**Comment by inhere** [comment]
FromRequest 原本是设计为直接验证request里面的数据，验证好了之后再绑定到 对应的结构体上，结构体上不用写验证规则
Struct()  则是需要先绑定好数据之后（比如 `gin c.ShouldBind(u)` ），再调用 `validate.Struct(u)` 验证,结构体上需要写验证规则

https://github.com/gookit/validate#use-on-gin-framework 我加了文档，如何绑定到gin

**Comment by NeroCho** [comment]
> FromRequest 原本是设计为直接验证request里面的数据，验证好了之后再绑定到 对应的结构体上，结构体上不用写验证规则
> Struct() 则是需要先绑定好数据之后（比如 `gin c.ShouldBind(u)` ），再调用 `validate.Struct(u)` 验证,结构体上需要写验证规则
> 
> https://github.com/gookit/validate#use-on-gin-framework 我加了文档，如何绑定到gin

谢谢，已解决
