### ISSUE TITLE
结构体如果嵌套了3层，第三层结构体没有设置required,但是任何字段都报错字段为必填

### ISSUE THREAD

**Issue by BrisyIOS** [gookit/validate#98]

**Comment by inhere** [comment]
能提供一个复现示例吗

**Comment by cpj555** [comment]
我刚用到也发现这个问题了 上来看看。。

**Comment by cpj555** [comment]
type MenuCreateRequest struct {
	Name        string      `json:"name" validate:"required"`
	Sequence    int         `json:"sequence"`                  // 排序值
	Icon        string      `json:"icon"`                      // 菜单图标
	Router      string      `json:"router"`                    // 访问路由
	ParentID    uint64      `json:"parent_id"`                 // 父级ID
	IsShow      int         `json:"is_show" validate:"in:0,1"` // 是否显示(1:显示 0:隐藏)
	Status      int         `json:"status" validate:"in:0,1"`  // 状态(1:启用 0:禁用)
	Memo        string      `json:"memo"`                      // 备注
	MenuActions MenuActions `json:"actions,omitempty"`
}

// MenuActions 菜单动作管理列表
type MenuActions []*MenuAction
// MenuAction 菜单动作对象
type MenuAction struct {
	Code      string              `json:"code" validate:"required"` // 动作编号
	Name      string              `json:"name" validate:"required"` // 动作名称
	Resources MenuActionResources `json:"resources,omitempty"`      // 资源列表
}


// MenuActionResources 菜单动作关联资源管理列表
type MenuActionResources []*MenuActionResource

// MenuActionResource 菜单动作关联资源对象
type MenuActionResource struct {
	ID       uint64 `json:"id"`                                                 // 唯一标识
	ActionID uint64 `json:"action_id"`                                          // 菜单动作ID
	Method   string `json:"method" validate:"required"` // 资源请求方式(支持正则)
	Path     string `json:"path" validate:"required"`                          // 资源请求路径（支持/:id匹配）
}

**Comment by anyone0034** [comment]
> 能提供一个复现示例吗

我也遇到了这个问题，这个bug修复了嘛。

**Comment by inhere** [comment]
还没的。这两天找时间看看处理下

**Comment by anyone0034** [comment]
> 还没的。这两天找时间看看处理下

好的，出现切片校验规则就会无效。

**Comment by inhere** [comment]
发布了 `1.3.0`， 可以更新看看

**Comment by inhere** [comment]
有问题说下，再打开
